fetch_character_html_data: str = "蔡徐坤鸡你太美𫮃𬺓𬙋耰𩾌𬙊𬶋𬶍𬭚𬭛陎𫵷鱲䲘鱣纕鸊鸏乾幹個豐餜餛闍淼溼擣𢷬蹵躕樐㯭艣艪"

# Test data for fetching entries with varying present information
fetch_character_info_section_data: dict[str, dict[str, bool]] = {
    "蔡": {
        "img_src": True,
        "pinyin": True,
        "zhuyin": True,
        "radical": True,
        "non_radical_stroke_count": True,
        "total_stroke_count": True,
        "simple_trad": False,
        "variant_characters": True,
        "unicode": True,
        "character_structure": True,
        "stroke_order": True,
        "wubi": True,
        "cangjie": True,
        "zhengma": True,
        "sijiao": True,
    },
    "徐": {
        "img_src": True,
        "pinyin": True,
        "zhuyin": True,
        "radical": True,
        "non_radical_stroke_count": True,
        "total_stroke_count": True,
        "simple_trad": False,
        "variant_characters": True,
        "unicode": True,
        "character_structure": True,
        "stroke_order": True,
        "wubi": True,
        "cangjie": True,
        "zhengma": True,
        "sijiao": True,
    },
    "坤": {
        "img_src": True,
        "pinyin": True,
        "zhuyin": True,
        "radical": True,
        "non_radical_stroke_count": True,
        "total_stroke_count": True,
        "simple_trad": False,
        "variant_characters": True,
        "unicode": True,
        "character_structure": True,
        "stroke_order": True,
        "wubi": True,
        "cangjie": True,
        "zhengma": True,
        "sijiao": True,
    },
    "张": {
        "img_src": True,
        "pinyin": True,
        "zhuyin": True,
        "radical": True,
        "non_radical_stroke_count": True,
        "total_stroke_count": True,
        "simple_trad": True,
        "variant_characters": True,
        "unicode": True,
        "character_structure": True,
        "stroke_order": True,
        "wubi": True,
        "cangjie": True,
        "zhengma": True,
        "sijiao": True,
    },
    "国": {
        "img_src": True,
        "pinyin": True,
        "zhuyin": True,
        "radical": True,
        "non_radical_stroke_count": True,
        "total_stroke_count": True,
        "simple_trad": True,
        "variant_characters": True,
        "unicode": True,
        "character_structure": True,
        "stroke_order": True,
        "wubi": True,
        "cangjie": True,
        "zhengma": True,
        "sijiao": True,
    },
    "荣": {
        "img_src": True,
        "pinyin": True,
        "zhuyin": True,
        "radical": True,
        "non_radical_stroke_count": True,
        "total_stroke_count": True,
        "simple_trad": True,
        "variant_characters": True,
        "unicode": True,
        "character_structure": True,
        "stroke_order": True,
        "wubi": True,
        "cangjie": True,
        "zhengma": True,
        "sijiao": True,
    },
    "和": {
        "img_src": True,
        "pinyin": True,
        "zhuyin": True,
        "radical": True,
        "non_radical_stroke_count": True,
        "total_stroke_count": True,
        "simple_trad": False,
        "variant_characters": True,
        "unicode": True,
        "character_structure": True,
        "stroke_order": True,
        "wubi": True,
        "cangjie": True,
        "zhengma": True,
        "sijiao": True,
    },
    "𬇙": {
        "img_src": True,
        "pinyin": False,
        "zhuyin": False,
        "radical": True,
        "non_radical_stroke_count": True,
        "total_stroke_count": True,
        "simple_trad": False,
        "variant_characters": False,
        "unicode": True,
        "character_structure": True,
        "stroke_order": False,
        "wubi": False,
        "cangjie": True,
        "zhengma": False,
        "sijiao": False,
    },
    "𫘝": {
        "img_src": True,
        "pinyin": False,
        "zhuyin": False,
        "radical": True,
        "non_radical_stroke_count": True,
        "total_stroke_count": True,
        "simple_trad": False,
        "variant_characters": False,
        "unicode": True,
        "character_structure": True,
        "stroke_order": False,
        "wubi": False,
        "cangjie": False,
        "zhengma": True,
        "sijiao": False,
    },
    "𪾢": {
        "img_src": True,
        "pinyin": False,
        "zhuyin": False,
        "radical": True,
        "non_radical_stroke_count": True,
        "total_stroke_count": True,
        "simple_trad": False,
        "variant_characters": False,
        "unicode": True,
        "character_structure": True,
        "stroke_order": False,
        "wubi": False,
        "cangjie": False,
        "zhengma": True,
        "sijiao": False,
    },
    "𦭜": {
        "img_src": True,
        "pinyin": True,
        "zhuyin": True,
        "radical": True,
        "non_radical_stroke_count": True,
        "total_stroke_count": True,
        "simple_trad": False,
        "variant_characters": False,
        "unicode": True,
        "character_structure": True,
        "stroke_order": True,
        "wubi": True,
        "cangjie": True,
        "zhengma": True,
        "sijiao": False,
    },
    "𫠊": {
        "img_src": True,
        "pinyin": True,
        "zhuyin": True,
        "radical": True,
        "non_radical_stroke_count": True,
        "total_stroke_count": True,
        "simple_trad": True,
        "variant_characters": False,
        "unicode": True,
        "character_structure": True,
        "stroke_order": False,
        "wubi": False,
        "cangjie": False,
        "zhengma": False,
        "sijiao": False,
    },
    "鿍": {
        "img_src": True,
        "pinyin": True,
        "zhuyin": True,
        "radical": True,
        "non_radical_stroke_count": True,
        "total_stroke_count": True,
        "simple_trad": False,
        "variant_characters": False,
        "unicode": True,
        "character_structure": True,
        "stroke_order": False,
        "wubi": False,
        "cangjie": False,
        "zhengma": False,
        "sijiao": False,
    },
    "𨱇": {
        "img_src": True,
        "pinyin": False,
        "zhuyin": False,
        "radical": True,
        "non_radical_stroke_count": True,
        "total_stroke_count": True,
        "simple_trad": False,
        "variant_characters": True,
        "unicode": True,
        "character_structure": True,
        "stroke_order": True,
        "wubi": True,
        "cangjie": False,
        "zhengma": True,
        "sijiao": False,
    },
    "𣸣": {
        "img_src": True,
        "pinyin": True,
        "zhuyin": True,
        "radical": True,
        "non_radical_stroke_count": True,
        "total_stroke_count": True,
        "simple_trad": False,
        "variant_characters": True,
        "unicode": True,
        "character_structure": True,
        "stroke_order": True,
        "wubi": True,
        "cangjie": False,
        "zhengma": True,
        "sijiao": False,
    },
}

# Test data fetching for entries that have definitions
fetch_definitions_section_data_1: dict = {
    "鸡": {
        "jī, ㄐㄧˉ": ["家禽，品种很多，翅膀短，不能高飞；雄性能报晓，雌性能生蛋：公～。母～。～雏。"],
        "英语": ["chicken"],
        "德语": ["Huhn  (S, Bio)"],
        "法语": ["poule,coq,poulet"],
    },
    "杉": {
        "shān, ㄕㄢˉ": ["常绿乔木，树干很高很直。木材白色，质轻，有香味，可供建筑和制器具用。"],
        "shā, ㄕㄚˉ": ["义同（一）：～木。～篙。"],
        "英语": ["various species of pine and fir"],
        "德语": ["Kiefer  (S)​,Tanne  (S)​,Zeder  (S)​,Kiefer  (S)​,Tanne, Fichte  (S)​,Zeder  (S)"],
        "法语": ["sapin de Chine,Cunninghamia lanceolata"],
    },
    "佚": {
        "yì, ㄧˋ": ["同“逸”。", "放荡：淫～。～游。", "美：～女。", "姓。"],
        "dié, ㄉㄧㄝˊ": ["古同“迭”，轮流，更替。"],
        "英语": ["indulge in pleasures; flee"],
        "德语": ["faul, müßig ,Yi  (Eig, Fam)"],
        "法语": ["oisif,fainéant,omettre"],
    },
    "𨚕": {
        "biàn, ㄅㄧㄢˋ": ["邑名。", "姓。"],
    }
}

# Test data fetching for entries that have no definitions
fetch_definitions_section_data_2: dict = {
    "𫚭": {},
    "𬺓": {},
    "𬙋": {},
    "𬟁": {},
    "𬸘": {},
    "𫷷": {},
}